### ISSUE TITLE
Updates of plugins need to be checked again

### ISSUE THREAD

**Issue by jarne** [poggit/poggit#159]
When submitting an update of a plugin, it takes really long sometimes until it has the status 'Approved' again. This is really annoying because users need to wait on the update and the old version is still shown on the 'Releases'-page.

In my case, some of our plugins got the status 'Checked' after an update, but the update is hidden from the users because the old version has still the status 'Approved'.

My suggestion would be that the status doesn't change when submitting an update. It's getting checked by the Poggit-team anyways, so another check for each update isn't really necessary.

**Comment by SOF3** [comment]
Some updates have many additions, and need another full review.

**Comment by SOF3** [comment]
We are indeed slow in reviewing plugins from Submitted to Checked these two months. But I believe that it is necessary that plugins must be fully re-reviewed before getting raised to Approved again (or wait for people to make it Voted), otherwise it's a slippery slope that may cause decreasing plugin quality.

**Comment by SOF3** [comment]
Anyway, it is up to reviewers' decision on time and confidence whether they can make it Approved or Checked. It is not something that can be changed in Poggit's software, so I am closing this issue.
