### ISSUE TITLE
Add a 'bump' button

### ISSUE THREAD

**Issue by lukeeey** [poggit/poggit#167]
It would be nice if, every so often, we could push a button to remind Poggit staff to review our plugin and approve it. To prevent spam, this could be every few days and only available for Checked plugins.

I thought of this because i submitted a [BlockSniper update](https://poggit.pmmp.io/p/BlockSniper/2.3.1) 2 days ago and Sandertv checked it. Because the approved version is displayed, users get an outdated version which will not work on their server. This isnt a big issue since *it's only 2 days*, but the time isnt so short with other plugins.

Another example is [PerWorldAlerts](https://poggit.pmmp.io/p/PerWorldAlerts/1.2). It's remained checked since the 19th February. It even supports the latest API.

**Comment by Thunder33345** [comment]
bump but i suggest once every week

**Comment by lukeeey** [comment]
Once every week but after 2 months once every 2 days.

**Comment by SOF3** [comment]
I see no reason why a Poggit reviewer should give extra attention to a plugin just because the author has bumped it. We already have a well-sorted review queue. If nobody wants to review it, it is because nobody has time/motivation, and bumping it won't give any extra motivation.

~~Creating this issue is a nice alternative way of bumping your own plugin though.~~

**Comment by lukeeey** [comment]
~~it's technically not my plugin though~~
