### ISSUE TITLE
please support other git services

### ISSUE THREAD

**Issue by djdisodo** [poggit/poggit#170]
some peoples will want to use self-hosted git service

**Comment by SOF3** [comment]
Self-hosted git service, no.
Other public Git services like GitLab, BitBucket, etc., worth considering.

**Comment by Thunder33345** [comment]
@SOF3 why not selfhosted doe?
some uses federated gitlab protocol, but i dont think they shall be supported via release system due to uncertainty of status and reliability
our release system should just work with Github and Gitlab

**Comment by SOF3** [comment]
The current design of Poggit totally relies on GitHub login and specific behaviour from GitHub. We need to do many changes if we support GitLab too, e.g. usernames from GitLab have to have a `~` prefix, etc. It might also open room for a lot of vulnerabilities since I'm not sure about the exact behaviour of GitLab (I'm not familiar with it).

**Comment by SOF3** [comment]
Unless we have people who don't use GitHub at all upvote this issue, I will not work on this :trollface:
