### ISSUE TITLE
about the old site

### ISSUE THREAD

**Issue by DDJTUSE** [poggit/poggit#230]
The old plugins site: https://forums.pocketmine.net/ has many good plugins that this new one does not have, and it is quite old, the plugins that are there, many people want and so do I!  If you are wondering "then why don't you download and install it on pocketmine?"  that's because I'm using aternos, not everyone can open ports on the router to use pocketmine, and since aternos only accepts plugins from poggit, it would be good if the creators of the plugins that are on the old site, brought them here, I don't know  how it works if anyone can download a plugin and put it here, i would even do it to be able to use the plugins and not to lie saying i made them

**Comment by SOF3** [comment]
All plugins on forums.pocketmine.net are seriously outdated. In particular, those explicitly tagged "Outdated" would require an entire rewrite to get updated.

In short, just assume the plugins on forums.pocketmine.net belong to another world. It has been 4 years since we moved here, and a lot has changed in these 4 years. Making a new plugin would most likely be easier than trying to update those old plugins.

**Comment by DDJTUSE** [comment]
> All plugins on forums.pocketmine.net are seriously outdated. In particular, those explicitly tagged "Outdated" would require an entire rewrite to get updated.
> 
> In short, just assume the plugins on forums.pocketmine.net belong to another world. It has been 4 years since we moved here, and a lot has changed in these 4 years. Making a new plugin would most likely be easier than trying to update those old plugins.

in this case, I just hope that the plugins are redone!  Thank you

**Comment by SOF3** [comment]
Poggit maintains the website, not the plugins. You can request plugins at https://forums.pmmp.io/forums/requests
