### ISSUE TITLE
Missing owner/author name in the plugin list API.

### ISSUE THREAD

**Issue by matcracker** [poggit/poggit#234]
When you get information from JSON of Poggit API there is not any owner/author name of plugin. Most of the time it is found in the "producers > Collaborator" entry but in some cases it is not.
Examples:
- https://poggit.pmmp.io/plugins.json?name=BedcoreProtect (there is not my name, only the translator)
- https://poggit.pmmp.io/plugins.json?name=MyPlot (there is not jasonwynn10)

The idea is to add an entry "producers > Owner" or correctly add the author inside the collaborator entry.

Thanks.

**Comment by JaxkDev** [comment]
So there’s two parts to this if I’ve looked at it rightly,
A, The plugin owner is sometimes put as an ‘Owner’ or ‘Collaborator’ on a release, from my tiny amount of testing you seem to be classed as owner if you add anyone on the producers list, or stay as a Collaborator if no one is added.
B, The API doesn’t include ‘Owner’ if the plugin owner is put in that ‘category’

**Comment by JaxkDev** [comment]
@SOF3 Is this not designed behaviour ?
If not this sql call statement need modifying, specifically the `IFNULL` https://github.com/poggit/poggit/blob/7af4ce0a25a4d5811b2c0904ac6809aa49b1e827/src/poggit/release/index/ReleaseListJsonModule.php#L110

**Comment by JaxkDev** [comment]
grr this is very annoying because it links to guess what, orgs.
There's no way to easily add user to contributor because repo_owner can be an organisation which is why i think sofe added the is null check because in orgs there'd always be contributors so it'll never show org name BUT with user owned repos and other contributors this is where it leaves the owner out because It assumes its an org by the looks of it...

**Comment by SOF3** [comment]
I was micro optimizing too much. Feel free to rewrite as appropriate.

**Comment by KygekDev** [comment]
I think this can easily be implemented by using `explode("/", $data["repo_name"])[0]`.

**Comment by SOF3** [comment]
@KygekDev the point is to distinguish when the owner is an org.
