### ISSUE TITLE
LICENSE detection not working for jojoe77777/Slapper

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit#236]
I'm attempting to submit Slapper 1.6.0, and the auto-detect LICENSE button doesn't pick up the common LGPL-3.0 license from the repo which has been there for the last 4 years.
https://github.com/jojoe77777/Slapper/blob/324b48dea27ed636f6a84f5afa7090cb2568eba0/LICENSE

**Comment by SOF3** [comment]
Was the license there in the previous releases? Poggit uses the value from last release instead of re-detecting for certain fields.

**Comment by dktapps** [comment]
Yes. See https://poggit.pmmp.io/p/Slapper/1.5.30.

**Comment by JaxkDev** [comment]
I have actually looked at this and it's weird githubs done this but essentially they no longer list lgpl-3.0 only lgpl-2.1 so when poggit (successfully) detects slapper using lgpl-3.0 it cross references this with githubs list (https://api.github.com/licenses) it wont find a match and so no default value is set.

If you go back to previous releases with 3.0 set if you look at the license space in the submission page for that release it will be blank because it no longer exists.

**Comment by JaxkDev** [comment]
Note the license is still on github but not on the most commonly used list anymore (the list poggit uses) (https://api.github.com/licenses)

https://api.github.com/licenses/lgpl-3.0

**Comment by SOF3** [comment]
Is this worth reporting as a bug to GitHub?

**Comment by JaxkDev** [comment]
I’ve just assumed it’s no longer a ‘commonly used’ license can if you want but not sure if they’ll do anything about it.

But this means the list is not ‘fixed’ or reliable so this does need to be thought through.

**Comment by JaxkDev** [comment]
@SOF3 Should we look at changing the license endpoint, github won't list all licenses only commonly used ones which can change depending on usage so never providing a comprehensive list.

Maybe https://github.com/github/choosealicense.com/tree/gh-pages/_licenses
(https://api.github.com/repos/github/choosealicense.com/contents/_licenses)

**Comment by JaxkDev** [comment]
Scratch that, could just get the repo’s license as sorted by GitHub as it will have the license key if known, we can use that otherwise it provides us with the LICENSE file content so we can use that under ‘custom’ type.

https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository

**Comment by jasonw4331** [comment]
I recommend using the SPDX license list for validation

https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json

**Comment by JaxkDev** [comment]
Should be alright, just use the SPDX id from GitHubs response
