### ISSUE TITLE
Suggestion: "Vanilla" category

### ISSUE THREAD

**Issue by HimbeersaftLP** [poggit/poggit#270]
I suggest adding a category named something like "vanilla mechanics" for plugins that extend PMMP with vanilla features that it's missing by default (i.e. https://poggit.pmmp.io/p/Netherite/1.2.1 or https://poggit.pmmp.io/p/Sponges/1.1.0).

**Comment by SOF3** [comment]
I think they suit quite well into mechanics.

**Comment by HimbeersaftLP** [comment]
I guess so, but it'd make it easier for newcomers to extend their server with missing features if it was a seperate category.

**Comment by JaxkDev** [comment]
Any verdict on this ? @SOF3

**Comment by SOF3** [comment]
I guess it doesn't hurt to add one more category. Doubt anyone uses them anyway :D

**Comment by NhanAZ** [comment]
btw
I think the staff should actively add categories to the plugin instead of letting the plugin authors do it.
Adding categories correctly will make it easier for users to find plugins.
Poggit allows authors to add any category they want, which makes it possible for some authors to add entire categories to their plugin, causing incorrect category search plugin results.
