### ISSUE TITLE
Stay signed in button

### ISSUE THREAD

**Issue by Dog2puppy** [poggit/poggit#34]
Below the 'Login with GitHub' button there should be a checkbox to stay logged in.

**Comment by Awzaw** [comment]
I stay logged in automatically - can you check if  your public IP address changes when this happens?

**Comment by Sandertv** [comment]
I remain logged in as well, can confirm that.

**Comment by Dog2puppy** [comment]
I have a static IP, so it never changes. It seems to happen only if I don't go to the website for a da yu or 2.

**Comment by Awzaw** [comment]
If it only happens after a few days I think this is the cause, and there's nothing we can do about it:

> Note, there is a limit to the number of tokens that are issued per user/application/scope combination. If your application requests enough tokens to go over one of the limits, older tokens will stop working.

from https://developer.github.com/v3/oauth/

**Comment by SOF3** [comment]
I don't even know what is "stay signed in". I only know one way of staying signed in without intended expiration, and I'm using it already.

I believe that, instead of logging out the user, if Poggit **thinks** the user is logged in (the session is retained), but the GitHub OAuth tokens no longer work, then errors will occur. I don't think Poggit is taught to intelligently forget deactivated old tokens.

I prefer to believe that there might be some server restart or server GC or whatever that caused the mentioned logout, although these reasons aren't likely either.

Sessions are stored with cookies. I doubt if client IP address has any relationship with the session.

**Comment by Dog2puppy** [comment]
@Awzaw @SOF3 Okay.

**Comment by Dog2puppy** [comment]
@SOF3 What if I taught poggit to forget old tokens.

**Comment by Awzaw** [comment]
I've now been logged in for about a week... if you are still getting this behaviour, are you sure your cookies aren't getting cleared somehow?

**Comment by Dog2puppy** [comment]
My cookies never clear, my ip is static, and it only happens if I'm inactive for over a day.

**Comment by Thunder33345** [comment]
but is a dont sign me in possible?
even tho the auth is relied on github

**Comment by SOF3** [comment]
@Thunder33345 since you're aware of it, ask GitHub for it.
