### ISSUE TITLE
Poggit Requires default branch use

### ISSUE THREAD

**Issue by jasonwynn10** [poggit/poggit#36]
When attempting to add a new repository to poggit, I did not add the master branch (because that has a website on it with no plugins) to the .poggit.yml and only added the plugins branch. Poggit automatically disabled that repository until I manually added the master branch to the config

**Comment by Awzaw** [comment]
Poggit doesn't require you to use 'master' branch, but it does use the github "Default Branch" setting for your repo. Either set that to 'plugins', or specify both 'master' and 'plugins' in poggit.yml and it will work.

**Comment by Awzaw** [comment]
According to SOF3 to avoid problems with this kind of setup the best approach is simply to commit the same .poggit.yml to all branches :-) You can also choose not to commit poggit.yml when enabling a project - there doesn't need to be a .poggit.yml file in the default branch as long as you add it manually to your non-default branch

**Comment by jasonwynn10** [comment]
I'll test that and see if it works

**Comment by SOF3** [comment]
I assume you to be mentioning about your jasonwynn10/YourCraftZ repo. According to my observation, the .poggit.yml in your master branch is unnecessary and can be removed. However you have to create it in your plugins branch. The pull request jasonwynn10/YourCraftZ#1 has been created, which possibly helps with your problem.

This issue remains opened as @Awzaw is assigned to improve documentation about multi-branching. However, since Poggit doesn't know which branch is your main plugin branch (because if you branch off your plugins branch to something else, Poggit can't know which branch you prefer to use as default), some web interface-related things on Poggit may be broken. For example, the link to project directories in the ProjectBuildPage (the `/ci/owner/repo/project` page) will remain linking to the master branch, which will end up in 404s.

I still strongly recommend you to set default branch (you can do so in the repo settings) to your plugins branch, or even put everything in the same branch but in separate directories.

**Comment by jasonwynn10** [comment]
Could there be a way to set the branch to add the poggit.yml to? maybe add a list of repository branches before committing the settings file to it?

**Comment by SOF3** [comment]
@jasonwynn10 you are complicating the issue :D Poggit tries to load most of the data from the .poggit.yml, and now you are asking to depend on something else, then why not entirely delete the .poggit.yml :D

The simple definition for which branch to place the .poggit.yml is, if you want Poggit to build that branch, .poggit.yml is mandatory, and if you don't want Poggit to build that branch, .poggit.yml is optional.

**Comment by jasonwynn10** [comment]
Okay, that makes more sense to me. Thank You.

**Comment by SOF3** [comment]
Since I haven't encountered anyone with this issue for more than two years, I am closing this. Poggit documentation is just... who reads them anyway?
